# Generated by Django 5.2.8 on 2025-11-20 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='reminder',
            old_name='latitude',
            new_name='target_lat',
        ),
        migrations.RenameField(
            model_name='reminder',
            old_name='longitude',
            new_name='target_lon',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='description',
        ),
        migrations.AddField(
            model_name='reminder',
            name='email',
            field=models.EmailField(default='test@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='reminder',
            name='radius',
            field=models.PositiveIntegerField(default=500),
        ),
        migrations.AddField(
            model_name='reminder',
            name='triggered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
