# Generated by Django 5.2.8 on 2025-11-23 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0002_rename_latitude_reminder_target_lat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
